from sqlalchemy import Column, Integer, String, Float
from .database import Base


class Gdsc(Base):
    __tablename__ = "gdsc"
    gdsc_id: int = Column(name="gdsc_id", type_=Integer, primary_key=True, index=True)
    drug_name: str = Column(name="drug_name", nullable=False, type_=String(400))
    drug_id: int = Column(name="drug_id", nullable=False, type_=Integer())
    source: str = Column(name="source", nullable=False, type_=String(40))
    sample_index: str = Column(name="sample_index", nullable=False, type_=String(100))
    predictions: float = Column(name="predictions", type_=Float(), nullable=True)
    predictions_std: float = Column(name="predictions_std", type_=Float(), nullable=True)
    quantile_score: float = Column(name="quantile_score", type_=Float(), nullable=True)
    experimental_min: float = Column(name="experimental_min", type_=Float(), nullable=True)
    experimental_median: float = Column(name="experimental_median", type_=Float(), nullable=True)
    experimental_max: float = Column(name="experimental_max", type_=Float(), nullable=True)
    model_mse: float = Column(name="model_mse", type_=Float(), nullable=True)
    model_corr: float = Column(name="model_corr", type_=Float(), nullable=True)
    transcr_ccle_neigh: str = Column(name="transcr_ccle_neigh", nullable=False, type_=String(400))
    transcr_ccle_neigh_celllinename: str = Column(name="transcr_ccle_neigh_celllinename", nullable=False, type_=String(400))
    transcr_ccle_neigh_oncotree: str = Column(name="transcr_ccle_neigh_oncotree", nullable=False, type_=String(400))
    response_ccle_neigh: str = Column(name="response_ccle_neigh", nullable=False, type_=String(400))
    response_ccle_neigh_celllinename: str = Column(name="response_ccle_neigh_celllinename", nullable=False, type_=String(400))
    response_ccle_neigh_oncotree: str = Column(name="response_ccle_neigh_oncotree", nullable=False, type_=String(400))
    transcr_tcga_neigh: str = Column(name="transcr_tcga_neigh", nullable=False, type_=String(400))
    transcr_tcga_neigh_diagnosis: str = Column(name="transcr_tcga_neigh_diagnosis", nullable=False, type_=String(400))
    transcr_tcga_neigh_site: str = Column(name="transcr_tcga_neigh_site", nullable=False, type_=String(400))
    response_tcga_neigh: str = Column(name="response_tcga_neigh", nullable=False, type_=String(400))
    response_tcga_neigh_diagnosis: str = Column(name="response_tcga_neigh_diagnosis", nullable=False, type_=String(400))
    response_tcga_neigh_site: str = Column(name="response_tcga_neigh_site", nullable=False, type_=String(400))
    putative_target: str = Column(name="putative_target", nullable=False, type_=String(400))
    top_local_shap_genes: str = Column(name="top_local_shap_genes", nullable=False, type_=String(400))
    recovered_target: str = Column(name="recovered_target", nullable=False, type_=String(3000))


class Prism(Base):
    __tablename__ = "prism"
    prism_id: int = Column(name="prism_id", type_=Integer, primary_key=True, index=True)
    drug_name: str = Column(name="drug_name", nullable=False, type_=String(400))
    drug_id: int = Column(name="drug_id", nullable=False, type_=Integer())
    source: str = Column(name="source", nullable=False, type_=String(40))
    sample_index: str = Column(name="sample_index", nullable=False, type_=String(100))
    predictions: float = Column(name="predictions", type_=Float(), nullable=True)
    predictions_std: float = Column(name="predictions_std", type_=Float(), nullable=True)
    quantile_score: float = Column(name="quantile_score", type_=Float(), nullable=True)
    experimental_min: float = Column(name="experimental_min", type_=Float(), nullable=True)
    experimental_median: float = Column(name="experimental_median", type_=Float(), nullable=True)
    experimental_max: float = Column(name="experimental_max", type_=Float(), nullable=True)
    model_mse: float = Column(name="model_mse", type_=Float(), nullable=True)
    model_corr: float = Column(name="model_corr", type_=Float(), nullable=True)
    transcr_ccle_neigh: str = Column(name="transcr_ccle_neigh", nullable=False, type_=String(400))
    transcr_ccle_neigh_celllinename: str = Column(name="transcr_ccle_neigh_celllinename", nullable=False, type_=String(400))
    transcr_ccle_neigh_oncotree: str = Column(name="transcr_ccle_neigh_oncotree", nullable=False, type_=String(400))
    response_ccle_neigh: str = Column(name="response_ccle_neigh", nullable=False, type_=String(400))
    response_ccle_neigh_celllinename: str = Column(name="response_ccle_neigh_celllinename", nullable=False, type_=String(400))
    response_ccle_neigh_oncotree: str = Column(name="response_ccle_neigh_oncotree", nullable=False, type_=String(400))
    transcr_tcga_neigh: str = Column(name="transcr_tcga_neigh", nullable=False, type_=String(400))
    transcr_tcga_neigh_diagnosis: str = Column(name="transcr_tcga_neigh_diagnosis", nullable=False, type_=String(400))
    transcr_tcga_neigh_site: str = Column(name="transcr_tcga_neigh_site", nullable=False, type_=String(400))
    response_tcga_neigh: str = Column(name="response_tcga_neigh", nullable=False, type_=String(400))
    response_tcga_neigh_diagnosis: str = Column(name="response_tcga_neigh_diagnosis", nullable=False, type_=String(400))
    response_tcga_neigh_site: str = Column(name="response_tcga_neigh_site", nullable=False, type_=String(400))
    putative_target: str = Column(name="putative_target", nullable=False, type_=String(400))
    top_local_shap_genes: str = Column(name="top_local_shap_genes", nullable=False, type_=String(400))
    recovered_target: str = Column(name="recovered_target", nullable=False, type_=String(3000))

