name: CLRP
channels:
  - defaults
dependencies:
  - python==3.10
  - pip:
      - mysql-connector-python
      - pandas
      - pip
      - pymysql
      - uvicorn
      - fastapi
      - requests
      - pydantic
      - strawberry-graphql
      - python-decouple
      - sqlalchemy==1.4.51


